#!/bin/bash -e

usage()
{
	echo 'Usage: dfhack-test [os] [bits] [command]' >&2
	echo 'os: linux or macosx' >&2
	echo 'bits: 32 or 64' >&2
	echo '(run inside the DF folder)' >&2
}

if [[ $# -ne 2 ]]; then
	usage
	exit 1
fi

os=$1
bits=$2
shift 2

if [[ "$os" != "linux" ]] || [[ "$bits" != "64" ]]; then
	echo '[temporary] Skipping tests for all platforms other than 64-bit Linux.'
	exit 0
fi

rm -f libs/libstdc++.so.6 # silence a warning when this gets deleted by DFHack

python3 /home/buildmaster/dfhack-native/travis/run-tests.py \
	--df_folder=. \
	--headless \
	--keep-status | \
while read -r line; do
	fd=1
	# lines containing light red text go to stderr
	if [[ "$line" == *$'\x1b[01;31m'* ]]; then
		fd=2
	fi

	# remove ANSI escape sequences
	perl -pe 's/\r//g and s/\x1b\[[0-9;]+m//g' <<<"$line" >&$fd
done
