#!/bin/bash -e

usage()
{
	echo 'Usage: dfhack-configure [os] [bits] [mode] [cmake args...]' >&2
	echo 'os: windows' >&2
	echo 'bits: 32 or 64' >&2
	echo 'mode: Release or RelWithDebInfo' >&2
}

if [[ $# -lt 3 ]]; then
	usage
	exit 1
fi

os=$1
bits=$2
mode=$3
shift 3

if [[ -z "$CCACHE_BASEDIR" ]] || [[ ! -d "$CCACHE_BASEDIR" ]]; then
	echo "The environment variable CCACHE_BASEDIR should be set to the closest parent directory of the source and build directories." >&2
	exit 2
fi

case $os in
windows)
	;;
*)
	usage
	exit 1
	;;
esac

case $bits in
32|64)
	;;
*)
	usage
	exit 1
	;;
esac

case $mode in
Release)
	;;
RelWithDebInfo)
	echo "* forcing build mode to Release" >&2
	mode=Release
	;;
*)
	usage
	exit 1
	;;
esac

. msvcenv-native.sh

wineserver -p
wine64 wineboot

CCACHE=/usr/local/bin/ccache-win

CC=cl CXX=cl cmake .. -GNinja -DDFHACK_BUILD_ARCH=$bits -DCMAKE_BUILD_TYPE=$mode -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_CROSSCOMPILING=ON -DCCACHE_EXECUTABLE=$CCACHE -DCMAKE_CXX_COMPILER_LAUNCHER=$CCACHE -DCMAKE_C_COMPILER_LAUNCHER=$CCACHE -DDFHACK_NATIVE_BUILD_DIR=/home/buildmaster/dfhack-native "$@" <&0

wineserver -k
wineserver -w
