#!/bin/bash -e

dir="$(pwd)"
while [[ ! -f "$dir/dfhack-clcache-env.sh" ]] && [[ "$dir" != "/" ]]; do
	dir="$(dirname "$dir")"
done
. "$dir/dfhack-clcache-env.sh"

make -j$(nproc) "$@" <&1

wineserver -w
