#!/bin/bash -e

dir="$(pwd)"
while [[ ! -f "$dir/dfhack-clcache-env.sh" ]] && [[ "$dir" != "/" ]]; do
	dir="$(dirname "$dir")"
done
. "$dir/dfhack-clcache-env.sh"

if [[ ! -z "$DFHACK_USE_NINJA" ]]; then
	ninja "$@" <&1
else
	make -j$(nproc) "$@" <&1
fi

wineserver -w
