#!/bin/bash

usage()
{
	echo 'Usage: dfhack-configure [os] [bits] [mode] [cmake args...]' >&2
	echo 'os: windows' >&2
	echo 'bits: 32 or 64' >&2
	echo 'mode: Release or RelWithDebInfo' >&2
}

if [[ $# -lt 3 ]]; then
	usage
	exit 1
fi

os=$1
bits=$2
mode=$3
shift 3

case $os in
windows)
	;;
*)
	usage
	exit 1
	;;
esac

case $bits in
32|64)
	;;
*)
	usage
	exit 1
	;;
esac

case $mode in
Release)
	;;
RelWithDebInfo)
	echo "* forcing build mode to Release" >&2
	mode=Release
	;;
*)
	usage
	exit 1
	;;
esac

. msvcenv-native.sh

wineserver -p
wine64 wineboot

CC=cl CXX=cl cmake .. -GNinja -DDFHACK_BUILD_ARCH=$bits -DCMAKE_BUILD_TYPE=$mode -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_CROSSCOMPILING=ON -DDFHACK_NATIVE_BUILD_DIR=/home/buildmaster/dfhack-native -DGITCOMMAND=$(which git) -DGIT_EXECUTABLE=$(which git) "$@" <&0
status=$?

wineserver -k
wineserver -w

exit $status
