#!/bin/bash -e

declare -a args

while (( "$#" )); do
	arg="$(perl -pe 's#(?<!\.dir)/home/buildmaster#Z:/home/buildmaster#g' <<<"$1" | perl -pe 's#(?<!\.dir)/opt/cmake#Z:/opt/cmake#g')"
	args+=("$arg")
	shift
done

#echo '[DFHack debug] rewrote command to '"$(basename "$0")"'.exe '"${args[*]}"

if [[ "$(basename "$0")" == "clcache" ]]; then
	if wine "$(basename "$0")" "${args[@]}" < /dev/null; then
		wineserver -w
		exit
	else
		echo "[DFHack] attempting again with clcache disabled."
		export CLCACHE_DISABLE=1
	fi
fi

wine "$(basename "$0")" "${args[@]}" < /dev/null

wineserver -w
