name: Build and Push Docker Image

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    strategy:
      matrix:
        IMAGE_TAG:
          - msvc
          # - gcc-4.8
          # - latest
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ matrix.IMAGE_TAG }}
          type=semver,pattern={{major}}.{{minor}},value=${{ matrix.IMAGE_TAG }}
          type=semver,pattern={{major}},value=${{ matrix.IMAGE_TAG }}
    - name: Build and push
      id: push
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:${{ matrix.IMAGE_TAG }}"
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
